baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Geeky Monkeys'
theme = 'mediumish-gohugo-theme'

[params]
	logo = "images/logo.jpg"
	description = "Lots of monkeys"

[params.index]
	title = "Jim Bones"
	subtitle = "Lets see what happens"
	mdtext = '''
	What is this!?!?!\
	**Just doing what I'm told. **\

### This is a markdown heading?
'''
alertbar=false


## Main menu
[[menu.main]]
	name = "Blog"
	weight = 100
	identifier = "blog"
	url = "/blog/"

